services:
  backend-api:
    build: ./maxiemprestimos
    container_name: maxiemprestimos
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/emprestimos_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=emprestimos_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  front-maxi-emprestimos:
    build: ./front-maxi-emprestimos
    container_name: front-maxi-emprestimos
    ports:
      - "80:80"
    depends_on:
      - backend-api

volumes:
  postgres_data:
